version: '{build}'
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration:
- Debug
- Release
platform:
- All VS
install:
- ps: >-
    Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-msvc.exe"

    .\rust-nightly-i686-pc-windows-msvc.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust" /COMPONENTS="rust,cargo,std" | Out-Default

    $env:Path += ";C:\Program Files (x86)\Rust\bin"

    rustc -Vv

    cargo -Vv
before_build:
- cmd: >-
    git submodule update --init --recursive

    nuget restore
build:
  project: VisualRust.sln
  parallel: true
  verbosity: normal
artifacts:
- path: bin\VisualRust.Setup.2015\Release\*.exe
- path: bin\VisualRust.Setup.2017\Release\*.exe