using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using VisualRust.Cargo;

namespace VisualRust.Project.Controls
{
    class CommandOutputTargetViewModel : IOutputTargetViewModel
    {
        public RelayCommand Execute { get; private set; }

        public CommandOutputTargetViewModel(Action action)
        {
            Execute = new RelayCommand(action);
        }

        #region IOutputTargetViewModel
        bool IOutputTargetViewModel.Bench
        {
            get
            {
                throw new InvalidOperationException();
            }
        }

        bool IOutputTargetViewModel.Doc
        {
            get
            {
                throw new InvalidOperationException();
            }
        }

        bool IOutputTargetViewModel.Doctest
        {
            get
            {
                throw new InvalidOperationException();
            }
        }

        bool IOutputTargetViewModel.Harness
        {
            get
            {
                throw new InvalidOperationException();
            }
        }

        bool IOutputTargetViewModel.IsAutoGenerated
        {
            get
            {
                return false;
            }
        }

        string IOutputTargetViewModel.Name
        {
            get
            {
                throw new InvalidOperationException();
            }
        }

        string IOutputTargetViewModel.Path
        {
            get
            {
                throw new InvalidOperationException();
            }
        }

        bool IOutputTargetViewModel.Plugin
        {
            get
            {
                throw new InvalidOperationException();
            }
        }

        string IOutputTargetViewModel.TabName
        {
            get
            {
                throw new InvalidOperationException();
            }
        }

        bool IOutputTargetViewModel.Test
        {
            get
            {
                throw new InvalidOperationException();
            }
        }

        public OutputTargetType Type
        {
            get
            {
                // Dirty hack to force this to be at the end of the list in the UI
                return (OutputTargetType)255;
            }
        }

        public RelayCommand Remove
        {
            get
            {
                return null;
            }
        }
        #endregion
    }
}
