using System;
using VisualRust.Cargo;

namespace VisualRust.Project.Controls
{
    public class OutputTargetViewModel : ViewModelBase, IOutputTargetViewModel
    {
        public OutputTargetType Type { get; private set; }

        readonly Manifest manifest;

        public string TabName { get { return this.Name; } }

        public string DefaultName { get { return manifest.Name; } }
        private string name;
        public string Name
        {
            get { return name ?? manifest.Name; }
            set
            {
                if(Set(ref name, value))
                {
                    RaisePropertyChanged("IsNameOverriden");
                    RaisePropertyChanged("Path");
                }
            }
        }
        public bool IsNameOverriden { get { return name != null; } } 

        
        public string DefaultPath { get { return Type.DefaultPath(Name ?? DefaultName); } }
        private string path;
        public string Path
        {
            get { return path; }
            set
            {
                if(Set(ref path, value))
                    RaisePropertyChanged("IsPathOverriden");
            }
        }
        public bool IsPathOverriden { get { return path != null; } } 
        
        private bool test;
        public bool Test
        {
            get { return test; }
            set { Set(ref test, value); }
        }
        
        private bool doctest;
        public bool Doctest
        {
            get { return doctest; }
            set { Set(ref doctest, value); }
        }
        
        private bool bench;
        public bool Bench
        {
            get { return bench; }
            set { Set(ref bench, value); }
        }
        
        private bool doc;
        public bool Doc
        {
            get { return doc; }
            set { Set(ref doc, value); }
        }
        
        private bool plugin;
        public bool Plugin
        {
            get { return plugin; }
            set { Set(ref plugin, value); }
        }

        private bool harness;
        public bool Harness
        {
            get { return harness; }
            set { Set(ref harness, value); }
        }

        public bool IsAutoGenerated { get { return false; } }

        public OutputTargetViewModel(Manifest m, OutputTarget t)
        {
            this.manifest = m;
            Type = t.Type;
            name = t.Name;
            path = t.Path;
            test = t.Test;
            doctest = t.Doctest;
            bench = t.Bench;
            doc = t.Doc;
            plugin = t.Plugin;
            harness = t.Harness;
        }
    }
}